from bs4 import BeautifulSoup
import json
from pathlib import Path
from datetime import datetime
from collections import Counter
from config import HTML_FILE, PARSED_DATA_FILE


class DropOrchestrator:
    """Orchestrator for parsing"""

    def __init__(self):
        self.soup = self.load_html(HTML_FILE)

        from parsers.mission_parser import MissionDropParser
        from parsers.relic_parser import RelicDropParser
        from parsers.sortie_parser import SortieDropParser
        from parsers.bounty_parser import (
            CetusBountyDropParser,
            SolarisBountyDropParser,  # Orb Vallis
            DeimosBountyDropParser,  # Cambion Drift
            ZarimanBountyDropParser,
            EntratiLabDropParser,  # Albrecht's Laboratories
            HexBountyDropParser,
        )
        from parsers.transient_parser import (
            TransientDropParser,
        )  # Dynamic Location Rewards

        self.mission_parser = MissionDropParser(self.soup)
        self.relic_parser = RelicDropParser(self.soup)
        self.sortie_parser = SortieDropParser(self.soup)
        self.cetus_bounty_parser = CetusBountyDropParser(self.soup)
        self.solaris_bounty_parser = SolarisBountyDropParser(self.soup)
        self.deimos_bounty_parser = DeimosBountyDropParser(self.soup)
        self.zariman_bounty_parser = ZarimanBountyDropParser(self.soup)
        self.entrati_lab_bounty_parser = EntratiLabDropParser(self.soup)
        self.hex_bounty_parser = HexBountyDropParser(self.soup)
        self.transient_parser = TransientDropParser(self.soup)

        self.all_drops = []
        self.parsed_at = datetime.now()

        # Store validation reports
        self.mission_report = None
        self.relic_report = None
        self.sortie_report = None
        self.cetus_bounty_report = None
        self.solaris_bounty_report = None
        self.deimos_bounty_report = None
        self.zariman_bounty_report = None
        self.entrati_lab_bounty_report = None
        self.hex_bounty_report = None
        self.transient_report = None

    def load_html(self, file_path: str | Path) -> BeautifulSoup:
        """Load HTML file"""
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                return BeautifulSoup(f.read(), "html.parser")

        except FileNotFoundError as e:
            raise FileNotFoundError(
                f'HTML file "{file_path}" not found. '
                "Please fetch data first (run in Mode 1)."
            ) from e

    def parse_all(self) -> tuple[list, dict]:
        """Parse everything and store validation reports"""
        # Parse Missions
        mission_drops, self.mission_report = self.mission_parser.parse()

        # Parse Relics
        relic_drops, self.relic_report = self.relic_parser.parse()

        # Parse Sorties
        sortie_drops, self.sortie_report = self.sortie_parser.parse()

        # Parse Bounties
        cetus_bounty_drops, self.cetus_bounty_report = self.cetus_bounty_parser.parse()
        solaris_bounty_drops, self.solaris_bounty_report = (
            self.solaris_bounty_parser.parse()
        )
        deimos_bounty_drops, self.deimos_bounty_report = (
            self.deimos_bounty_parser.parse()
        )
        zariman_bounty_drops, self.zariman_bounty_report = (
            self.zariman_bounty_parser.parse()
        )
        entrati_lab_bounty_drops, self.entrati_lab_bounty_report = (
            self.entrati_lab_bounty_parser.parse()
        )
        hex_bounty_drops, self.hex_bounty_report = self.hex_bounty_parser.parse()

        # Parse Dynamic Location Rewards
        transient_drops, self.transient_report = self.transient_parser.parse()

        self.all_drops = (
            mission_drops
            + relic_drops
            + sortie_drops
            + cetus_bounty_drops
            + solaris_bounty_drops
            + deimos_bounty_drops
            + zariman_bounty_drops
            + entrati_lab_bounty_drops
            + hex_bounty_drops
            + transient_drops
        )

        len_all_drops = {
            "mission_drops": len(mission_drops),
            "relic_drops": len(relic_drops),
            "sortie_drops": len(sortie_drops),
            "cetus_bounty_drops": len(cetus_bounty_drops),
            "solaris_bounty_drops": len(solaris_bounty_drops),
            "deimos_bounty_drops": len(deimos_bounty_drops),
            "zariman_bounty_drops": len(zariman_bounty_drops),
            "entrati_lab_bounty_drops": len(entrati_lab_bounty_drops),
            "hex_bounty_drops": len(hex_bounty_drops),
            "transient_drops": len(transient_drops),
            "total_drops": len(self.all_drops),
        }

        return self.all_drops, len_all_drops

    def get_validation_report(self) -> dict:
        """
        Get comprehensive validation report for ALL data
        Uses the reports already generated by parsers
        """
        reports = {}

        # Use the reports already generated during parsing
        reports["missions"] = self.mission_report
        reports["relics"] = self.relic_report
        reports["sorties"] = self.sortie_report
        reports["cetus_bounty"] = self.cetus_bounty_report
        reports["solaris_bounty"] = self.solaris_bounty_report
        reports["deimos_bounty"] = self.deimos_bounty_report
        reports["zariman_bounty"] = self.zariman_bounty_report
        reports["entrati_lab_bounty"] = self.entrati_lab_bounty_report
        reports["hex_bounty"] = self.hex_bounty_report
        reports["transient"] = self.transient_report

        # Calculate overall stats based on ACTUAL data being used
        total_drops = len(self.all_drops)

        # Count errors across all parsers
        all_errors = []
        all_warnings = []

        if self.mission_report:
            all_errors.extend(self.mission_report.get("errors", []))
            all_warnings.extend(self.mission_report.get("warnings", []))

        if self.relic_report:
            all_errors.extend(self.relic_report.get("errors", []))
            all_warnings.extend(self.relic_report.get("warnings", []))

        if self.sortie_report:
            all_errors.extend(self.sortie_report.get("errors", []))
            all_warnings.extend(self.sortie_report.get("warnings", []))

        if self.cetus_bounty_report:
            all_errors.extend(self.cetus_bounty_report.get("errors", []))
            all_warnings.extend(self.cetus_bounty_report.get("warnings", []))

        if self.solaris_bounty_report:
            all_errors.extend(self.solaris_bounty_report.get("errors", []))
            all_warnings.extend(self.solaris_bounty_report.get("warnings", []))

        if self.deimos_bounty_report:
            all_errors.extend(self.deimos_bounty_report.get("errors", []))
            all_warnings.extend(self.deimos_bounty_report.get("warnings", []))

        if self.zariman_bounty_report:
            all_errors.extend(self.zariman_bounty_report.get("errors", []))
            all_warnings.extend(self.zariman_bounty_report.get("warnings", []))

        if self.entrati_lab_bounty_report:
            all_errors.extend(self.entrati_lab_bounty_report.get("errors", []))
            all_warnings.extend(self.entrati_lab_bounty_report.get("warnings", []))

        if self.hex_bounty_report:
            all_errors.extend(self.hex_bounty_report.get("errors", []))
            all_warnings.extend(self.hex_bounty_report.get("warnings", []))

        if self.transient_report:
            all_errors.extend(self.transient_report.get("errors", []))
            all_warnings.extend(self.transient_report.get("warnings", []))

        # Group issues by type for easy fixing
        error_types = Counter(e["reason"] for e in all_errors)
        warning_types = Counter(w["reason"] for w in all_warnings)

        reports["overall"] = {
            "total_drops": total_drops,
            "error_count": len(all_errors),
            "warning_count": len(all_warnings),
            "data_integrity": (
                (total_drops - len(all_errors)) / total_drops if total_drops > 0 else 0
            ),
            "errors_by_type": dict(error_types),
            "warnings_by_type": dict(warning_types),
        }

        return reports

    def print_validation_details(self, max_errors: int = 10) -> None:
        """
        For debugging/fixing in CLI in DEV mode
        """
        report = self.get_validation_report()

        print("\n" + "=" * 60)
        print("DETAILED VALIDATION REPORT")
        print("=" * 60)

        # Show mission errors
        if report["missions"] and report["missions"]["errors"]:
            print("\nMISSION ERRORS:")
            for error in report["missions"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["missions"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['missions']['errors']) - max_errors} more"
                )

        # Show relic errors
        if report["relics"] and report["relics"]["errors"]:
            print("\nRELIC ERRORS:")
            for error in report["relics"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["relics"]["errors"]) > max_errors:
                print(f"  ... and {len(report['relics']['errors']) - max_errors} more")

        # Show sortie errors
        if report["sorties"] and report["sorties"]["errors"]:
            print("\nSORTIE ERRORS:")
            for error in report["sorties"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["sorties"]["errors"]) > max_errors:
                print(f"  ... and {len(report['sorties']['errors']) - max_errors} more")

        # Show cetus bounty errors
        if report["cetus_bounty"] and report["cetus_bounty"]["errors"]:
            print("\nCETUS BOUNTY ERRORS:")
            for error in report["cetus_bounty"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["cetus_bounty"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['cetus_bounty']['errors']) - max_errors} more"
                )

        # Show solaris bounty errors
        if report["solaris_bounty"] and report["solaris_bounty"]["errors"]:
            print("\nSOLARIS BOUNTY ERRORS:")
            for error in report["solaris_bounty"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["solaris_bounty"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['solaris_bounty']['errors']) - max_errors} more"
                )

        # Show deimos bounty errors
        if report["deimos_bounty"] and report["deimos_bounty"]["errors"]:
            print("\nDEIMOS BOUNTY ERRORS:")
            for error in report["deimos_bounty"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["deimos_bounty"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['deimos_bounty']['errors']) - max_errors} more"
                )

        # Show zariman bounty errors
        if report["zariman_bounty"] and report["zariman_bounty"]["errors"]:
            print("\nZARIMAN BOUNTY ERRORS:")
            for error in report["zariman_bounty"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["zariman_bounty"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['zariman_bounty']['errors']) - max_errors} more"
                )

        # Show entrati lab bounty errors
        if report["entrati_lab_bounty"] and report["entrati_lab_bounty"]["errors"]:
            print("\nENTRATI LAB BOUNTY ERRORS:")
            for error in report["entrati_lab_bounty"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["entrati_lab_bounty"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['entrati_lab_bounty']['errors']) - max_errors} more"
                )

        # Show hex bounty errors
        if report["hex_bounty"] and report["hex_bounty"]["errors"]:
            print("\nHEX BOUNTY ERRORS:")
            for error in report["hex_bounty"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["hex_bounty"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['hex_bounty']['errors']) - max_errors} more"
                )

        # Show transient errors
        if report["transient"] and report["transient"]["errors"]:
            print("\nTRANSIENT ERRORS:")
            for error in report["transient"]["errors"][:max_errors]:
                print(
                    f"  Row {error['index']} -> Reason: {error['reason']} - Item: {error['item']}"
                )
            if len(report["transient"]["errors"]) > max_errors:
                print(
                    f"  ... and {len(report['transient']['errors']) - max_errors} more"
                )

        # Show warnings summary
        total_warnings = report["overall"]["warning_count"]
        if total_warnings > 0:
            print(f"\nWARNINGS: {total_warnings} total")
            for warning_type, count in report["overall"]["warnings_by_type"].items():
                print(f"  - {warning_type}: {count}")

        print("=" * 60)

    def save_parsed_data(self) -> str:
        """Save parsed data to file"""
        data = {
            "source": "WarframeDropOrchestrator",
            "parsed_at": self.parsed_at.isoformat(),
            "drops": self.all_drops,
        }

        with open(PARSED_DATA_FILE, "w") as f:
            json.dump(data, f, indent=2)

        return f'\n✓ Saved {len(self.all_drops)} drops to "{PARSED_DATA_FILE}"'
